name: Animal Accord
favicon: null
layout_spectrum: 0.7129335198551416
typography_spectrum: 0.2003324159886688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9185614404268563
  lightness: 0.4860710073262453
  saturation: 0.07183344406075776
  rhythmicContrast: 0.1045980651397258
purpose: []
